### ISSUE TITLE
Error while calling mod and assigning threads

### ISSUE THREAD

**Issue by vahidAK** [bioinfomaticsCSU/deepsignal#22] opened 2019-10-17 01:12 UTC
Hi @PengNi 
I am calling modification from the extracted feature file. After running for a while the software gives me this error:
return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
I would appreciate if you could help me with this matter.
BTW: another problem I face is that no matter how many threads you define for the deepsignal in nproc when extracting features or calling mods on CPU, it will take all the available threads.
Thanks,
Vahid.

**Comment by PengNi** [comment] 2019-10-17 01:23
@vahidAK , could you give a more complete log, which can help to locate the specific line in the script that raised the error? This is a error I didn't met before.

The threads problem may caused by the tensorflow. Sorry we haven't figure out how to solve it (refer to #3 task1).

**Comment by vahidAK** [comment] 2019-10-17 01:54
Sure! here is the more complete log:  
    
2019-10-16 15:46:36.698999: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:7 with 29925 MB memory) -> physical GPU (device: 7, name: Tesla V100-SXM2-32GB, pci bus id: 0000:8a:00.0, compute capability: 7.0)                                                                           Process Process-2:                                                                                                      Traceback (most recent call last):                                                                                        File "/projects/vakbari_prj/anaconda3/envs/deepsignal_gpu/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap                                                                                                                      self.run()                                                                                                            File "/projects/vakbari_prj/anaconda3/envs/deepsignal_gpu/lib/python3.6/multiprocessing/process.py", line 93, in run      self._target(*self._args, **self._kwargs)                                                                             File "/projects/vakbari_prj/anaconda3/envs/deepsignal_gpu/lib/python3.6/site-packages/deepsignal-0.1.6-py3.6.egg/deepsignal/call_modifications.py", line 186, in _call_mods_q                                                                     pred_str, accuracy = _call_mods(features_batch, sess, model, init_learning_rate)                                      File "/projects/vakbari_prj/anaconda3/envs/deepsignal_gpu/lib/python3.6/site-packages/deepsignal-0.1.6-py3.6.egg/deepsignal/call_modifications.py", line 140, in _call_mods                                                                       [model.activation_logits, model.prediction], feed_dict=feed_dict)                                                     File "/projects/vakbari_prj/anaconda3/envs/deepsignal_gpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 900, in run                                                                                                      run_metadata_ptr)                                                                                                     File "/projects/vakbari_prj/anaconda3/envs/deepsignal_gpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1104, in _run                                                                                                    np_val = np.asarray(subfeed_val, dtype=subfeed_dtype)                                                                 File "/projects/vakbari_prj/anaconda3/envs/deepsignal_gpu/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray                                                                                                                return array(a, dtype, copy=False, order=order)                                                                     ValueError: setting an array element with a sequence.

**Comment by PengNi** [comment] 2019-10-17 02:31
@vahidAK , can you give me a sample of your input file? I'm not sure but I think the format of the input may be wrong. Not all lines in the input file are wrong, maybe one line somewhere.

**Comment by vahidAK** [comment] 2019-10-17 02:48
Yes! I think the problem is with the input. My input is big file

**Comment by PengNi** [comment] 2019-10-17 03:17
@vahidAK , these two lines look fine to me. Did you split the extracted_feature file for parallel run? If you did, how did you split it?

**Comment by vahidAK** [comment] 2019-10-17 03:19
No, I separated my fast5 files and separation was at fast5 level

**Comment by PengNi** [comment] 2019-10-17 03:29
@vahidAK , I'd really appreciate it if you send me an sample input file for debug (onedrive or google drive or some other way).

Also, I suggest you to call mods from fast5 files directly, skip the extract_features step, see if this error is still raised.

**Comment by vahidAK** [comment] 2019-10-17 03:41
Thanks, @PengNi ,
Sure! but first, let me try once more maybe there was sth wrong during extracting features.
Regarding callin mods from fast5s, I actually did that but it just starts running without doing anything when I look at the log file.

**Comment by vahidAK** [comment] 2019-10-21 05:42
Hi @PengNi ,
I extracted the features again and called modification again. This time it worked just fine, so maybe I did something wrong in feature extraction.

**Comment by PengNi** [comment] 2019-10-21 06:19
@vahidAK ，OK, now I'm closing this issue. If you have any other problem, please tell me.

**Closed by PengNi** 2019-10-21 06:19 UTC
Labels: bug
